language: node_js
node_js:
  - "7"
before_install:
  - npm install jscodesniffer
cache:
  directories:
    - "node_modules"
script:
   - npm i
   - node jscs.js app.js --standard=Jquery --report-full
   - npm run dev
notifications:
  email:
    on_failure: always
    on_success: never

